<div class="container p-2 text-dark">
    <div class="ratio ratio-21x9">
    <iframe width="882" height="496" src="https://www.youtube.com/embed/SxkQnxHwtbI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <div class="container p-2 text-dark text-start ">
        <h1 class="intitle"><font  color="#660000" face='Century'><i>PREZENTAREA BISERICII FORTIFICATE DIN BIERTAN</i></font></h1>

        <div class="container-fluid sbtitle">
            <h2><font face="Verdana" size="5" color="#4d0000"><b>Biserica</b></font></h2>
            <div class="container-fluid">
                <p>Complexul arhitectural medieval din Biertan este alcătuit din biserica și centura de fortificații, toate amplasate în centrul așezării, pe un deal. Biserica de tip hală ocupa partea centrală a complexului, fiind construită între anii 1490 și 1520 în stilul gotic târziu, fiind ultima din Transilvania înălțată în acest stil. Construcție monumentală, de mari dimensiuni, are trei hale de înălțimi egale. Intrarea se face prin trei porți: de vest, de nord și de sud. Altarul poliptic al bisericii, cel mai mare din țară cu cele 28 de panouri pictate ale sale, a fost realizat între 1483 și 1513. Amvonul, sculptat în piatră, din 1500, este opera meșterului Ulrich din Brașov, cu o puternică influență sud-germană. </p>
                <p>Stranele din cor sunt caracterizate de George Oprescu astfel: „Mobilierul este de speță rară și foarte valoros. Stalurile, adică stranele din cor, de la începutul secolului al XIV-lea, sunt decorate cu benzi de ornamente gotice... Este decorația ce o întâlnim pe mobilele de acest fel din Germania și Elveția, cu nimic inferioare acestora, așa încât putem zice că la Biertan se găsesc strane, lucrate la noi, de tâmplari ardeleni, care ar putea figura în orice mare muzeu de artă aplicată”.</p>
                <p>Ușa sacristiei, cu un sistem complicat de 19 încuietori, a fost realizată de meșterii locali în anul 1515, fiind premiată la Expoziția Mondială din 1900 de la Paris. Constituie un exemplu reprezentativ de manufactură săsească medievală, datorită intarsiilor și a sistemului original de închidere, care funcționează și astăzi. Fortificațiile din jur sunt considerate drept cele mai puternice din Transilvania, de la o cetate țărănească. Are trei rânduri de ziduri, 6 turnuri și 3 bastioane construite în etape diferite începând cu secolul al XIV-lea. La partea superioară are un coridor de apărare, ceasul și clopotele. Turnul „mausoleu” este amplasat la nord-est și are la parter un mausoleu care adăpostește, din 1913, mormintele prelaților acestei biserici. </p>
                <p>Lespezile au fost realizate de Nikolaus Elias din Sibiu. Turnul catolicilor, situat pe latura sudică, a adăpostit capela rezervată catolicilor netrecuți la reformă.</p>
                <p>În biserică există o orgă, cea mai veche informație cu privire la aceasta datând din 1523, când este menționat organistul Bartholomäus. După câteva restaurări, s-a ajuns la orga existentă în prezent, cu 1290 de tuburi, 2 claviaturi, pedalier și 25 de registre, care datează din 1869 și a fost realizată de maestrul Carl Hesse din Viena.</p>
                <p>Pe vremuri, în bastionul estic se afla „carcera”, unde erau închiși, timp de două săptămâni, cuplurile (soț și soție) care se certau și intenționau să divorțeze. În camera de mici dimensiuni, având o masă mică și un singur pat, comunitatea sașilor le punea la dispoziție o singură farfurie, un singur tacâm și o singură cană pentru apă. Se spune că, în acele circumstanțe, doar o singură pereche a rămas neclintită în hotărârea inițială de a divorța, toate celelalte cupluri ieșind de acolo împăcate, fără a se mai apela la justiție. În partea de sud-vest se afla Turnul Slăninilor. În secolul al XVI-lea s-a construit cea de-a treia centură de ziduri pe laturile de est, vest și sud ale cetății. Turnul Închisorii era situat în partea de nord-vest, dar în 1840 a fost demolat pentru a se construi o școală. Pe centura a treia au fost ridicate Turnul de Poartă pe latura sudică și Turnul Țesătorilor în partea de vest. Accesul în interior spre biserică se face printr-o scară acoperită, lungă de 100 m, care pornește din piața centrală a satului, de lângă turnul paznicului. </p>
                <p>La capătul de sus al scării, lângă biserică se poate vedea un bolovan mare, pe care, duminica erau așezați cei care „făceau rele” în cursul săptămânii, spre a fi văzuți de întreaga comunitate. Acesta era considerat un mijloc de a-i educa și integra în colectivitatea așezării. Astăzi, această veche așezare săsească este cunoscută datorită bisericii-cetate, inclusă în 1993 pe lista monumentelor patrimoniului mondial a UNESCO. Biserica-cetate de aici, cu hramul Sfânta Maria, a fost restaurată prin donații făcute de originari din Biertan răspândiți în Europa, Statele Unite ale Americii și Australia. Șeful proiectului de restaurare, arhitectul Hermann Armeniu Fabini, a fost distins în 1991 cu medalia „Europa Nostra”.</p>
                <p>În anul 1775, în apropierea Biertanului, în „pădurea Chimdru” a fost descoperit un obiect ritual, cunoscut sub numele de Donariul de la Biertan, des invocat pentru a argumenta prezența unei populații creștine vorbitoare de limbă latină în Transilvania secolului al IV-lea.</p>
            </div>
        </div>
        
        <div class="container-fluid sbtitle">
            <h2><font face="Verdana" size="5" color="#4d0000"><b>Altarul</b></font></h2>
            <div class="container-fluid">
                <p>Altarul, aflat în partea de nord a bisericii, este construit în stilul gotic târziu și are forma de triptic. Altarul a fost construit de către meșteșugari din Nürnberg și Viena între anii 1483 și 1513. Acesta conține 28 de picturi cu scene din viața lui Isus Cristos, scene din viața Fecioarei Maria, scena Botezului Domnului, scena Tăierii Împrejur și diferite alte picturi care reprezintă sfinți din cultul catolic.</p>
                <p>Unicitatea acestui altar este dată de numărul mare de picturi. Se consideră că acest altar este unic în Europa. În perioada în care biserica s-a aflat în administrarea cultului romano-catolic, în mijlocul altarului se găsea o statuie a Fecioarei Maria, care era patroana bisericii. În locul statuii se găsește acum un crucifix. </p>
                <p>Partea principală a altarului este formată dintr-un crucifix care îi reprezintă pe Fecioara Maria, pe Isus Cristos și pe Maria Magdalena, care îmbrățișează crucea.</p>
                <p>În ansamblu, altarul are o înălțime de 489 cm și o lățime de 567 cm. Altarul central măsoară 211 x 132 x 41 cm (înălțime x lățime x adâncime). Aripile altarului măsoară cu cadru 211 x 139 cm (înălțime x lățime). Suprafața pictată a plăcilor intermediare fixe măsoară 94 x 50 cm fiecare. Panourile de pe interior măsoară 94 x 59 cm, cele ale exterioară 94 x 124 cm. Piesele de aripă imobilizate au o dimensiune de 211 x 140 cm. Predela este de 106 cm înălțime și 270 cm lățime. Panoul său central are o dimensiune de 97 x 67 cm (suprafață vopsită: 80 x 51 cm). Aripile predelei măsoară 97 x 67 cm (suprafață pictată: 80 x 51 cm). Sculpturile din altar au înălțimile de 80,5 cm (Maria), 80 cm (Ioan), 65 cm (Maria Magdalena) și 100 cm (Hristos).</p>
            </div>
        </div>

    </div>
</div>