<div class="container p-2 text-dark">
    <div class="ratio ratio-21x9">
    <iframe width="882" height="496" src="https://www.youtube.com/embed/L2_g_FDMsl8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <div class="container p-2 text-dark text-start ">
        <h1 class="intitle"><font color="#660000" face='Century'><i>PREZENTAREA BISERICII FORTIFICATE DIN VISCRI</i></font></h1>

        <div class="container-fluid">
            <h2></h2>
            <div class="container-fluid">
                <p>În Viscri mai dăinuie, bine conservată, una dintre cele mai pitorești și - în pofida dimensiunilor nu prea mari - monumentale cetăți țărănești săsești, ce cuprinde între zidurile sale una dintre puținele biserici-sală romanice ale secolului XIII. Particularitățile monumentului au preocupat pe mulți cercetători iar enigmele lui au putut fi dezlegate abia prin săpăturile întreprinse în 1970-1971 de către arheologul Mariana Dumitrache, care prezintă rezultatele lor într-un studiu amplu Cercetări arheologice și ale istoriei arhitecturii în zona Rupei, apărut în „Forschungen zur Volks- und Landeskunde”, vol. 21, nr. 2, 1978. În prezentarea monumentului preluăm cele constatate asupra istoriei construcției, concluzii obținute pe baza investigațiilor cercetătoarei. </p>
                <p>Poziția retrasă a așezării explică și apariția sa relativ târzie în documente. Abia pe la 1400, „Alba ecclesia" (alias Viscri) apare într-un registru al localităților pentru plata impozitului datorat episcopatului, al comitatului de Rupea (Kosd). Pe la 1500, Viscri este enumerată printre comunele libere ale Scaunului de Rupea, cu 51 de gospodării, trei păstori, un dascăl și doi săraci. Aici, ca și în alte comune, vechimea bisericii confirmă că așezarea coloniștilor germani a luat ființă la sfârșitul secolului XII când a fost colonizată și partea apuseană a viitorului Scaun al Rupei. Biserica-sală romanică, cum mai există în zona Rupei doar în Homorod (biserica-sală din Criț aparținea deja stilului de trecere de la romanic la gotic), a avut o predecesoare care a fost parțial inclusă în acest edificiu. Coloniștii germani (care s-au așezat în Viscri ca imigranți după domnia regelui Geza al II-lea, adică după 1162, ca „alii Flandrenses", în ultimul sfert al secolului XII) au găsit pe promontoriul din nord-estul comunei actuale o mică capelă. Aceasta era construită din calcar alb-verzui, avea formă rectangulară, cu absidă semicirculară spre răsărit, iar unicele podoabe erau pietrele cubice ecarisate ce formau colțurile sălii și începutul absidei, o arcadă semicirculară a intrării sudice. Sala avea un tavan plat, absida o semicalotă (lungimea capelei era de 13,5 m, a sălii de 9,80 m, lățimea sălii în vest de 7,8 m și în est de 8 m). După piesele descoperite în mormintele dinăuntrul și din afara capelei, monede și cercei de tâmplă de la începutul secolului XII, aceasta se datează între 1100-1120, ca aparținând unui grup de secui ce păzeau în acest punct granița statului maghiar feudal, înaintea sosirii coloniștilor germani. </p>
                <p>Existența capelei părăsite a dispensat pe coloniști de truda ridicării unei bazilici romanice cu trei nave, cum s-au construit în cele mai multe așezări săsești în decursul secolului XIII pe "pământul crăiesc". Adaptarea capelei s-a efectuat în etape, în concordanță cu evoluția socială a coloniștilor și condițiile istorice respective. Așa cum rezultă din analiza și interpretarea cercetărilor arheologice, capela s-a folosit, în prima etapă a evoluției așezării săsești, fără lărgire planimetrică, construindu-se doar o tribună de vest, susținută de patru arcade semicirculare, purtate de trei coloane cilindrice. Ipoteza aceasta este susținută de cele trei capiteluri romanice datate unanim în prima jumătate a secolului XIII, conservate în corul bisericii. Cel mai mare dintre ele (având suprafața de 48x48 cm) e așezat pe un segment de coloană, puțin scobit pe suprafața superioară, servind drept cristelniță.</p>
                <p>Fiecare din laturile rotunjite în partea inferioară, lăsând canturile să apară ca niște ciubuce semicirculare, este decorată, în partea superioară, printr-un scut central puțin reliefat și două jumătăți de scuturi laterale, cele două capiteluri mai mici având suprafața de 42x44 cm, fiind la fel ornamentate și având pe una din laturi patru mici scuturi egale. După forma ornamentării, capitelurile erau vizibile pe toate laturile, deci stăteau libere, folosirea lor ca intermediar între fusurile celor trei coloane și cele patru arcuri ale tribunei fiind foarte plauzibilă, nu li se poate găsi o amplasare mai potrivită. Datarea în prima jumătate a secolului XIII ar corespunde și timpului în care asemenea tribune s-au construit - e drept, în alt chip - în bazilicile din zona Sebeșului, dar aici ne preocupă funcția și nu forma tribunei de vest care, la Gârbova și Miercurea, a servit de asemeni unei familii de greavi sași. Turnul de locuit, construit la 4 m distanță în vest de capelă, amintește donjonul greavilor de la Câlnic și Gârbova, la fel forma ovală a incintei cu care s-a înconjurat cetatea cuprinzând vechiul cimitir cu capelă. </p>
                <p>Deoarece Viscri n-a fost niciodată proprietate nobiliară, numai familia greavului, conducătorul obștii sătești, a ridicat turnul de locuință, în a doua jumătate a secolului XIII spre folosință personală. Întrucât temelia turnului taie un mormânt, avem dovada că el a fost clădit ulterior capelei, când locul nu mai servea ca cimitir. De altfel, turnul e construit din alt material decât capela, anume din bazalt gri. Parterul nu are deschideri, poartă o boltă în leagăn pe axa est-vest, ca și catul al doilea, legat de cel inferior și de cel superior prin scări de piatră tăiate în grosimea zidului. Intrarea semicirculară în turn se află pe latura estică, accesibilă printr-o sară mobilă. De la al doilea cat în sus, nivelele aveau metereze înalte de 1.60 m, în nișe evazate spre interior, destinate arcașilor.</p>
                <p>Către sfârșitul secolului XIII, stingându-se probabil familia de greavi, aflăm din trei documente că un magister Akus dorește să cumpere satul, ceea ce nu s-a întâmplat. Cetatea trece, în secolul XIV, în posesia obștii, care modifică mai întâi partea estică a capelei, demolând convexitatea absidei și construind, în prelungirea pereților laterali ai acesteia, un cor devenit trapezoidal, închis în est, cu absidă semicirculară sprijinită de șapte contraforturi. Pe latura nordică a sălii, sacristia s-a construit înainte de modificarea corului, căci daca s-ar fi construit după ridicarea noului cor ar fi fost adosată acestuia și nu sălii. De altfel, sacristia veche, divizată printr-un perete transversal, a fost folosită parțial ca osuar. Presupunem că deja în această fază corul a primit o boltă, pereții de sud și nord prezentând o înclinare ce poate însemna nașterea unei bolți. </p>
                <p>A treia perioadă de construcție, situată în prima jumătate a secolului XVI, coincide cu fortificarea bisericii. Prin prelungirea pereților laterali ai capelei s-a racordat biserica-sală la donjon. În parterul său s-a creat o intrare pe latura estică, devenită acum peretele de vest al bisericii, intrare printr-un toc de piatră în arc frânt, cu ambrazură al cărei profil - baghetă semicilindrică între două cavete - este aproape identic cu ambrazura intrării din peretele nordic al bisericii-sală din Homorod, cu diferența că aici este închisă semicircular. Prin scările din grosimea zidului se ajunge la nivelele superioare, în al patrulea nivel, meterezul estic a fost transformat în intrare spre podul bisericii, fiind acoperit, ca toate meterezele turnului, în partea îngustă a nișei, cu lespezi, în cea evazată, cu bârne, acoperit de o mică streașină, deasupra căreia s-a mai înălțat zidul turnului cu un metru pentru guri de tragere deschise sub acoperișul în piramidă scundă. Pentru a putea folosi la tragere și ferestrele mici, în dreptul lor s-a construit o platformă. În partea de vest, prelungită, s-a creat un al doilea portal al sălii. Corul și sala au fost boltite în leagăn cu penetrații și nervuri de teracotă, sistem obișnuit în bisericile săsești pe la anul 1500. </p>
                <p>Pentru întărirea părții de est a bisericii, corul a fost înălțat poligonal și înconjurat de un al doilea rând de contraforturi ce se unesc sus prin arcadele semicirculare pentru a susține parapetul unui cat de apărare, în spatele arcadelor devansate deschizându-se mașiculiuri. Alte contraforturi s-au adosat laturilor de nord și de sud ale sălii, care s-au înclinat sub presiunea bolții, creându-le astfel o contrapresiune. Această măsură de protecție s-a dovedit ineficace, bolta fisurându-se pe alocuri și devenind periculoasă. În 1743, bolțile au fost înlocuite printr-un tavan casetat în sală și unul cu stucatură în cor. Tavanul casetat se acordă cu balustradele de lemn pictate și cu mobilierul bisericii; el e așezat deasupra ferestrelor gotice ale laturii de sud. Concomitent, s-a demolat și catul de apărare de deasupra corului, așezându-se acoperișul direct peste arcadele de apărare. Forma semicirculară a arcului triumfal s-a dovedit a nu fi romanica; el a fost înălțat pe colțurile vechii abside a capelei, arcul propriu-zis fiind din cărămidă și datând din secolul XVIII. Tot atunci s-a construit noua sacristie pe latura de nord a corului între două contraforturi. De aceste transformări amintește o inscripție de pe arcul triumfal indicând anul 1743. </p>
                <p>Ferestrele actuale ale corului au fost transformate, dar la cercetarea pereților s-au găsit urme ale unei ferestre romanice în estul absidei, iar ale uneia în arc frânt pe latura de sud, ambele datând din timpul transformării gotice a corului. Mari fragmente de fresce au fost descoperite, dar pictura a fost parțial distrusă la înălțarea corului. Peretele de nord al sălii ce nu are ferestre a fost de asemenea împodobit cu pictură, căreia i s-au suprapus câteva inscripții. Nișa din peretele de sud al corului a rămas de la vechea absidă a capelei, ea fiind boltită cu o arcadă din piatră (largă de 38 cm), intradosul ei fiind străbătut în centru de un ciubuc de piatră. Strane cu picturi fitomorfe gotice și renascentiste, datate 1694, sunt așezate de-a lungul peretelui de vest; tribunele de lemn, cu balustradele lor pictate, datează din 1717, iar stranele de pe latura de sud din 1783. Acest mobilier pictat rustic conferă o notă aparte, intimă, interiorului, prezentând totodată o valoare etnografică. </p>
                <p>Din incinta ovală a secolului XIII s-au păstrat sectoarele de sud, est și nord-est, zidul din piatră de râu și de câmp, atingând între 5,5-7 m înălțime. Poarta a fost probabil întotdeauna situată în sud-est, drumul urcând spre ea panta lină a promontoriului. În cursul fortificării, la începutul secolului al XVI-lea, sectorul sud-estic a fost dotat cu două turnuri și două bastioane. Turnul din sud, cu trei nivele și coridor de apărare devansat pe console din lemn, și bastionul de sud sunt unite sub același acoperiș un patru ape cu coamă lungă și adosate incintei în exterior, ca și bastionul din est. Inițial acesta purta același coridor de apărare, în cele trei nivele intrându-se din curtea cetății. În secolul XIX bastionul din est și-a pierdut nivelul de apărare, caturile inferioare au fost transformate în locuințe cu încălzire, iar catul superior a servit, până în anii 1960, pentru păstrat slănina. Nivelele inferioare ale bastionului de sud au fost comasate într-o singură sală mare, cu intrare pe latura de est, numai catul superior și-a păstrat meterezele late cu chenare din stejar și butuci turnanți ce le puteau închide. Coridorul de apărare și acoperișul bastionului de sud sunt unite cu cele ale turnului de sud. Turnul de poartă a fost așezat în spatele intrării, în incintă. Greutatea celor patru caturi este suportată de puternicii pereți laterali și de două arcuri întinse peste parterul boltit în leagăn, cele patru colțuri fiind sprijinite de contraforturi masive. </p>
                <p>Intrările spre caturile superioare, situate pe latura apuseană, erau accesibile inițial numai prin scări mobile, acum însă turnul din sud este legat de coridorul de apărare al bastionului și al turnului de sud printr-o platformă aflată în fața acestui turn la cel de-al treilea nivel, spre care urcă două scări de lemn. Între turnul de poartă și cel din sud se deschide o intrare pentru pietoni, cu ușă din lemn armată cu benzi de fier late de 10 cm, spre care duc scări largi de piatră, în curte pământul fiind mult ridicat față de exterior. </p>
                <p>Panta abruptă din vest, mai puțin expusă atacului, a fost întărită în secolul XVII, printr-un zid rectangular, ce cuprinde sectorul nord-vestic al incintei, două turnuri devansate, plasate în nord și vest (cel din nord, cu trei nivele fiind construit în 1630 de către arhitectul Johann Hartman, turnul de vest, cu patru nivele, ridicat în 1648-49). Turnurile clădite pe panta platoului sunt mult mai înalte în exterior decât în incintă, unde al doilea cat al lor se află la nivelul solului. În al treilea nivel se intra din coridorul de apărare ce înconjura incinta pe latura interioară, unde se aflau gurile de turnare și meterezele situate la 1,30 m sub coroana zidului. Ambele turnuri din secolul XVII au coridoare de apărare cu parapet de paiantă, ulterior îmbrăcat în scânduri. Nivelul superior al turnului de vest, cu mici ferestre spre nord și sud, iar în colțul de nord-est cu un orificiu pentru evacuarea fumului din vatră, servea ca locuință preotului în caz de asediu. Intrările situate spre curte au tocuri de stejar, nivelele separate prin platforme din lemn sunt prevăzute cu meterezele descrise mai sus. </p>
                <p>În secolul XVIII s-a construit un al doilea cordon de zid în jurul cetății, păstrat azi la înălțimea de numai un metru, cu lipsuri pe laturile de nord-est și sud-est. În incintă, coridorul de apărare a fost înlocuit printr-un șopron, acoperit într-o singură pantă, ce coboară de pe coroana curtinei către un zid mai scund, ridicat la 3-4 m distanță de curtină, și având 19 mari intrări dreptunghiulare., șopronul nefiind despărțit de ziduri transversale și servind la adăpostirea hambarelor de cereale. În 1970-71 cetatea a fost temeinic restaurată, reconstruindu-se coridorul de apărare al bastionului de est, iar după 1990 a intrat în patrimoniul mondial UNESCO. </p>
                
            </div>
        </div>

    </div>
</div>