<div class="container p-2 text-dark">
    <div class="ratio ratio-21x9">
        <iframe width="882" height="496" src="https://www.youtube.com/embed/ikEyXslvNHE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="container p-2 text-dark text-start ">
        <h1 class="intitle"><font color="#660000" face='Century'><i>PREZENTAREA PALATULUI CULTURII</i></font></h1>

        <div class="container-fluid">
            <h2></h2>
            <div class="container-fluid">
                <p>Palatul din centrul Iaşilor, conceput în spiritul palatelor comunale din Europa de Vest, este o îmbinare fericită a mai multor stiluri arhitecturale: neogotic, romantic și neobaroc. Marcând puternic arhitectura vechii capitale a Moldovei, Palatul s-a impus ca o adevarată efigie încă de la apariţia ei în peisajul urbei.</p>
                <p>Palatul de Justiție și Administrație din Iași, construit între anii 1906-1925 după planurile arhitectului I.D. Berindey, s-a impus prin dimensiunile sale remarcabile. Astfel, turnul central al clădirii, care atinge 55 de metri înălțime, făcea ca Palatul să fie considerat în epocă cea mai înaltă clădire din oraș cu o amprentă la sol de 7330 mp și o suprafață desfășurată de 34.236, 35 mp.</p>
                <p>În afara monumentalităţii și frumuseţii ei, clădirea se distingea prin instalaţii şi echipamentele tehnice moderne, achiziţionate din Germania, precum şi prin feroneria realizată de Casa Haug și de renumitele firme franceze Krieger, Mericier și Bagvès. Mobilierul Palatului de Justiţie, în stil neogotic, a fost proiectat şi realizat în celebrele ateliere Albert Goumain din Paris şi de către firma Mappel din Anglia.</p>
                <p>Edificiul se deschide printr-un hol generos - Holul de onoare, conceput în stil neogotic, spaţiu care se finalizează cu o boltă în ogivă decorată cu vitralii. Decorațiunile spatiului au fost concepute în două etape diferite: epoca de început, până în anul 1914, numită epoca lui Carol I (1866-1914), și epoca lui Ferdinand I (1914-1927), diferențiate prin stilul în care acestea au fost realizate. Epoca lui Carol este preponderent neoclasică, epoca lui Ferdinand este predominant barocă, îmbinată cu Art Nouveau. Este cunoscută implicarea reginei Maria, o mare iubitoare de Art Nouveau, în cea de a doua etapă, în Sala Voievozilor găsindu-se și monograma acesteia.</p>
                <p>În prima perioadă de edificare, stilul folosit a fost sobru și sever, în a doua etapă ornamentele s-au multiplicat, iar elementele decorative au fost marcate puternic de baroc: capitelurile compozite, console în acoladă decorate cu elemente florale și vegetale sau console simple și elegante neoclasice, frize decorative cu elemente vegetale, florale sau zoomorfe și multe scuturi heraldice, multe cu semnificație istorică heraldică, multe doar decorative. Sigur a doua etapă a fost preferată de Berindey, acesta fiind un mare arhitect al detaliilor, care a excelat în realizarea acestora. Arcadele în arc frânt, ornamentate cu muluri, sunt realizate alături de arce în plin cintru, arce aplatizate (cu un cintru sau trei cintre, mâner de coș) ornamentate cu elemente artistice (fleuroni, mascaroni și blazoane). </p>
                <p>Balconul în consolă a fost conceput cu un parapet traforat cu baluştri în acoladă și ornamentat cu o friză cu elemente zoomorfe. Scutul heraldic este prezent în întreaga zonă şi se integrează desăvârşit în ansamblul ornamentelor între care apare aproape obsesiv simbolul mascheronului. </p>
                <p>Remarcabilă este şi compoziţia circulară realizată în mozaicul pardoselii. Este vorba de un Bestiarum gotic, în care sunt înfăţişate tot felul de animale fantastice: acvile bicefale, dragoni, grifoni, himere şi lei. Două rozete mai mici, identice, se află şi la extremităţile holului de la primul etaj. </p>
                <p>Mozaicul din holul central al Palatului este o reproducere fidelă a rozetei din biserica abaţiei Saint-Pierre-sur-Dives (1235-1245), din nordul Franţei (departamentul Calvados, regiunea Basse Normandie). Modelul din secolul XIII era realizat în plăci de teracotă şi nu în mozaic. Prin reluarea acestui model, specific unei catedrale gotice, arhitectul Berindey a dorit să confere edificiului său o atmosferă de sacralitate.</p>
                <p>Scările monumentale simetrice sunt construite din marmură de Carrara, iar parapetul este realizat din baluştri în acoladă, decoraţi cu acvile cu scut, ce simbolizează deschiderea de drumuri. Marmura este albă, cu o venatură discretă, podestele sunt realizate din mozaic în model cu dale de şah, identice ca mărime cu cele de la etajul I, însă diferite la culoare (alb şi roz prăfuit). Dalele albe sunt realizate din marmură, cele colorate din stuco-marmură.</p>
                <p>Arcele în ogivă, specifice stilului neogotic, prezintă numeroase elemente decorative, în stil neobaroc, iar în câmp scuturi heraldice de dimensiuni mari. Bolta nervurată și bogat ornamentată este susținută de coloane simple şi canelate ale căror capiteluri compozite încântă privitorul cu elemente florale atent concepute.</p>
                <p>Sala Voievozilor, situată la etaj, este cea mai frumoasă şi monumentală încăpere a palatului, fiind ornamentata distinct de celelalte sali. Numele sălii se datorează unei celebre galerii de portrete ale domnilor Moldovei, pornind de la Decebal, Traian şi Aurelian, trecând apoi la întemeietorii statului medieval şi continuând seria conducătorilor acestui teritoriu până la regele Carol al II-lea. În zona de vest a sălii se află un monumental şemineu de marmură, decorat cu un basorelief care reprezintă un „Arbore istoric”, împodobit cu portretele celor mai însemnaţi domni ai Moldovei, în vârful căruia tronează portretul regelui Ferdinand.</p>
                <p>Intrarea în sala „Henri Coandă” este străjuită de două socluri rămase astăzi fără busturile inițiale. Acestea păstrează încă inscripționate numele foștilor miniștri de justiție Matei B. Cantacuzino (1855-1926) şi Gheorghe Mârzescu (1834-1901). Cele două busturi erau puse în valoare de fundaluri fastuoase, realizate din „mozaic bizantin”. Acest element arată că, probabil, inițial, cele două socluri erau destinate unor busturi regale, idee la care s-a renunțat pe parcurs. În perioada comunistă cele două busturi au fost înlăturate, ambele personaje fiind indezirabile regimului. Bustul lui Matei Cantacuzino realizat de R. Hette, în 1925, se află astăzi în amfiteatrul ce îi poartă numele din cadrul Facultății de Drept din Iași. Bustul lui Gheorghe Mârzescu este considerat dispărut.</p>
                <p>În perioada în care edificiul din Iaşi a fost Palat de Justiţie şi Administraţie, Sala „Henri Coandă” era destinată Curții cu Juri. Amplasarea centrală și decoraţiunile speciale subliniază însemnătatea deosebită a încăperii. Despre stucăturile din partea de sus a sălii se ştia că acestea sunt opera sculptorului Emil Wilhelm August Becker, sculptor al Casei regale. Se știe că arhitectul I. D. Berindey, care prezida Societatea Produselor Tehnice „H. Coandă” din Bucureşti, a cerut „găsirea” unui material mai ieftin care să imite textura şi sunetul lemnului de stejar. Acest material a fost inventat de Henri Coandă (numit bois-ciment de celebrul inventator) şi este întâlnit în mai multe săli din Palat. Totodată, de remarcat este şi faptul că sursa de inspiraţie în realizarea tavanului acestei săli  a fost  Westminster Hall din Londra, unde  s-a născut Parlamentul Regatului Unit al Marii Britanii.  Construcţia, realizată în anul 1512 ca reşedinţă a regilor Angliei,  a fost refăcută ulterior, în anul 1834, după un incendiu devastator. </p>
                <p>Dincolo de arhitectură, ceasornicul din turnul Palatului Culturii a contribuit în mod deosebit la faima clădirii. Acesta moștenea amintirea orologiului instalat în turnul portii Curții Domnești la 1728 și care a dat, multă vreme, ritmurile orașului.</p>
                <p>Instalarea unui orologiu cu carillon este în sine o opțiune romantică, întrucât construirea acestui gen de mecanisme se afla în ultima fază de evoluție istorică. Aceasta era o idee retro, în acord cu spiritul clădirii.</p>
                <p>Ceasornicul Palatului este un orologiu cu trei cadrane, având diametrul de 3,24 m. Acele ceasului măsoară 1,25m și respectiv 0,90 m. De la mecanismul central, mișcarea este transmisă prin axuri și grupuri de roți dințate conice, acelor celor trei cadrane ale ceasornicului. Mecanismul se încărca automat, la 12 ore, cu ajutorul unei greutăți de 120 kg, ce se ridica la o înălțime de 8 m. Printr-un sistem ingenios, ceasornicul din turn acționa în mod sincron 25 de ceasuri aflate în diverse săli ale Palatului; acestea au dispărut în timpul războiului. La fiecare oră exactă, orologiul din turnul Palatului Culturii cântă „Hora Unirii”. Melodia, înregistrată pe un tambur cu diametrul de 35 cm, printr-un număr de 69 de știfturi, este redată de un sistem de opt clopote acordate, care alcătuiesc mecanismul carillonului, aflat la etajul al patrulea al turnului.</p>
                <p>Vitraliile cadranelor ceasului sunt decorate cu cele 12 zodii. Potrivit arhitectului I.D. Berindey, cei doi oșteni, pictați în frescă şi care străjuiesc ceasul, sunt plăieșii lui Dragoș Vodă, descălecătorul Moldovei.</p>
                <p>Primul Război Mondial și anii grei ce au urmat au amânat realizarea finisajelor, pentru mai mulți ani, făcând ca inaugurarea oficială să aibă loc abia la 11 octombrie 1925, în prezența familiei regale, regele Ferdinand și regina Maria. În anul 1955, vechiul Palat de Justiție a devenit Palat al Culturii, găzduind unele din cele mai de seamă instituții culturale ale țării, reunite astăzi sub denumirea de Complexul Național Muzeal „Moldova” Iași care cuprinde patru muzee de talie națională: Muzeul de Istorie a Moldovei, Muzeul Științei și Tehnicii „Ștefan Procopiu”, Muzeul Etnografic al Moldovei, Muzeul de Artă, și Centrul de Cercetare şi Conservare-Restaurare a Patrimoniului Cultural.</p>

            </div>
        </div>

    </div>
</div>